apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: swishkube-grafana-ca-certificate
  namespace: swish-analytics
spec:
  isCA: true
  commonName: identity.grafana.swishkube.lan
  secretName: swishkube-grafana-ca-tls
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 8760h # 12 months
  renewBefore: 6570h # 9 months
  issuerRef:
    name: swishkube-root-ca
    kind: ClusterIssuer
    group: cert-manager.io